language: python
python:
  - "2.6"
  - "2.7"
install: 
  - pip install flake8
  # the following are installed because its needed for postgres tests to run
  - pip install psycopg2
  - pip install mock
  - pip install pycountry
  - pip install coveralls
  - python setup.py install
  - pip install 'trytond_nereid_test>=3.0,<3.1'
script:
  - coverage run setup.py test
  - python setup.py test_on_postgres
  - flake8 .
after_success:
  coveralls
